server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        - id: license-service
          uri: lb://license-service
          predicates:
            - Path=/api/license/**
          filters:
            - StripPrefix=0

        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


jwt:
  secret: your_very_long_and_secure_secret_key_at_least_256_bits_long_for_hs256
  expiration: 3600000 # 1 hour    

